name: Not a Sophist
favicon: null
layout_spectrum: 0.88683
typography_spectrum: 0.9154349346645176
title: Intellectual Integrity and the Pursuit of Truth
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6f6ea'
    - '#231e0b'
    - '#737141'
    - '#a8a56e'
    - '#e5e262'
  brandStrength: 0.3125
  lightness: 0.125
  saturation: 0.1881191344000399
  rhythmicContrast: 0.75
purpose: []
