name: Not a Sophist
favicon: null
layout_spectrum: 0.88904
typography_spectrum: 0.83238
title: Intellectual Integrity and the Pursuit of Truth
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#aef1ff'
    - '#000000'
    - '#c8c4bd'
    - '#686868'
    - '#273336'
  brandStrength: 0.3125
  lightness: 0.125
  saturation: 0.1881191344000399
  rhythmicContrast: 0.75
purpose: []
